"""Integration tests for the Kimi-K3 engine (kimik3.c).

Validates that the engine:
  - Builds cleanly (make kimik3)
  - Parses K3 config.json (nested text_config + linear_attn_config)
  - Loads both MXFP4-native and colibri-int8 expert snapshots
  - Runs end-to-end (MLA + KDA + Stable LatentMoE + dense MLP)
  - Produces deterministic output (same input -> same tokens twice)
  - Honours PPL=1 (teacher-forced NLL) mode
  - Reports expert cache hit/miss counters

The tiny K3 model is generated by tools/make_kimik3_tiny.py (no network, no
PyTorch) — 4 layers, 4 experts, hidden=64, vocab=256, MXFP4 packed experts.
The MXFP4 <-> int8 path is exercised by tools/convert_kimik3.py.

Run: python -m unittest tests.test_kimik3 -v
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

C_DIR = Path(__file__).resolve().parents[1]
ENGINE = C_DIR / "kimik3"
MAKE = shutil.which("make")
PY = sys.executable


def _run(cmd, env=None, cwd=None, timeout=120):
    """Run a command, return CompletedProcess. Throws on timeout."""
    return subprocess.run(
        cmd, cwd=cwd or C_DIR, env=env, text=True,
        capture_output=True, timeout=timeout,
    )


def _build_engine():
    """Ensure the kimik3 binary is built. Returns True on success."""
    if ENGINE.exists():
        # Force rebuild so we test current source, not a stale binary.
        _run([MAKE, "kimik3"])
    else:
        _run([MAKE, "kimik3"])
    return ENGINE.exists()


def _generate_tiny_model(out_dir):
    """Generate a tiny K3 model into out_dir. Idempotent per-out_dir."""
    if not (Path(out_dir) / "model.safetensors").exists():
        r = _run([PY, "tools/make_kimik3_tiny.py", "--out", str(out_dir)])
        if r.returncode != 0:
            raise RuntimeError(f"make_kimik3_tiny failed: {r.stderr}")
    return Path(out_dir)


def _run_engine(snap, cap=16, ref=None, extra_env=None, timeout=60):
    """Run ./kimik3 on a snapshot, return CompletedProcess."""
    env = dict(os.environ, SNAP=str(snap))
    if extra_env:
        env.update(extra_env)
    args = [str(ENGINE), str(cap)]
    if ref is not None:
        args.append(str(ref))
    return _run(args, env=env, timeout=timeout)


def _parse_engine_output(text):
    """Extract structured fields the engine prints to stdout."""
    out = {"raw": text}
    for line in text.splitlines():
        if line.startswith("[CFG]"):
            out.setdefault("cfg_lines", []).append(line)
        elif line.startswith("Reference:"):
            out["reference"] = [int(x) for x in line.split(":", 1)[1].split()]
        elif line.startswith("C engine :"):
            out["c_engine"] = [int(x) for x in line.split(":", 1)[1].split()]
        elif line.startswith("Matching tokens:"):
            num, den = line.split(":", 1)[1].strip().split("/")
            out["matching"] = (int(num), int(den))
        elif line.startswith("Expert cache hit rate:"):
            pct = float(line.split(":")[1].split("%")[0])
            out["hit_rate_pct"] = pct
            # extract (hit=N miss=M)
            tail = line.split("(hit=", 1)[1]
            h, m = tail.split(" miss=")
            out["hits"] = int(h); out["miss"] = int(m.rstrip(")"))
        elif line.startswith("PEAK RSS:"):
            out["peak_rss_gb"] = float(line.split(":")[1].strip().split()[0])
        elif line.startswith("Speed:"):
            out["tok_per_s"] = float(line.split(":")[1].split()[0])
        elif line.startswith("TF-NLL:"):
            # Format: "TF-NLL: %.4f nats/token over %d tokens  |  ppl = %.2f"
            parts = line.split()
            out["tf_nll"] = float(parts[1])
            out["tf_tokens"] = int(parts[4])  # "over <N> tokens"
            out["tf_ppl"] = float(parts[-1])
    return out


class KimiK3BuildTest(unittest.TestCase):
    """Build-system tests: the kimik3 target compiles with the standard CFLAGS."""

    @unittest.skipUnless(MAKE, "make is required")
    def test_kimik3_target_compiles(self):
        r = _run([MAKE, "-n", "kimik3"])  # dry-run to inspect command
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("kimik3.c", r.stdout)
        self.assertIn("-fopenmp", r.stdout)
        # output binary is named kimik3 (or kimik3.exe on Windows)
        self.assertRegex(r.stdout, r"-o kimik3(\.exe)?(\s|$)")

    @unittest.skipUnless(MAKE, "make is required")
    def test_kimik3_binary_exists_after_build(self):
        r = _run([MAKE, "kimik3"])
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertTrue(ENGINE.exists(), "kimik3 binary not created")

    @unittest.skipUnless(MAKE, "make is required")
    def test_install_target_lists_kimik3(self):
        """make install must install kimik3 alongside colibri and olmoe."""
        r = _run([MAKE, "-n", "install"])
        self.assertEqual(r.returncode, 0, r.stderr)
        # install recipe should mention kimik3 binary installation
        self.assertIn("kimik3", r.stdout)


class KimiK3ConfigTest(unittest.TestCase):
    """Config parsing: K3 nests under text_config + linear_attn_config."""

    @classmethod
    def setUpClass(cls):
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")
        cls.tiny = _generate_tiny_model(C_DIR / "kimik3_tiny")

    def _run_cfg(self, snap):
        # Engine requires a ref.json — the tiny model ships with one.
        ref = snap / "ref.json"
        return _run_engine(snap, cap=8, ref=ref)

    def test_config_reports_expected_dims(self):
        r = self._run_cfg(self.tiny)
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        # First [CFG] line: dims
        cfg1 = out["cfg_lines"][0]
        self.assertIn("hidden=64", cfg1)
        self.assertIn("layers=4", cfg1)
        self.assertIn("experts=4", cfg1)
        self.assertIn("topk=2", cfg1)
        self.assertIn("shared=2", cfg1)
        self.assertIn("vocab=256", cfg1)
        # Layer breakdown: dense=1 (KDA+dense MLP), MLA=1, KDA=2 (KDA+MoE)
        self.assertIn("dense=1", cfg1)
        self.assertIn("MLA=1", cfg1)
        self.assertIn("KDA=2", cfg1)

    def test_config_reports_attention_dims(self):
        r = self._run_cfg(self.tiny)
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        cfg2 = out["cfg_lines"][1]
        # q_lora=32 kv_lora=32 qk_nope=16 qk_rope=8 v_head=16
        self.assertIn("q_lora=32", cfg2)
        self.assertIn("kv_lora=32", cfg2)
        self.assertIn("qk_nope=16", cfg2)
        self.assertIn("qk_rope=8", cfg2)
        self.assertIn("v_head=16", cfg2)
        # KDA dims: kda_heads=4 kda_hd=16 short_conv=4
        self.assertIn("kda_heads=4", cfg2)
        self.assertIn("kda_hd=16", cfg2)
        self.assertIn("short_conv=4", cfg2)


class KimiK3ForwardTest(unittest.TestCase):
    """Forward pass: engine runs end-to-end and produces output."""

    @classmethod
    def setUpClass(cls):
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")
        cls.tiny = _generate_tiny_model(C_DIR / "kimik3_tiny")

    def test_engine_runs_on_mxfp4_snapshot(self):
        """MXFP4 native path: dequantize experts on demand."""
        r = _run_engine(self.tiny, cap=8, ref=self.tiny / "ref.json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        # Must produce some tokens (matching not required — random weights)
        self.assertIn("c_engine", out, f"no C engine output: {r.stdout}")
        self.assertGreaterEqual(len(out["c_engine"]), 1)
        # Engine should report cache stats
        self.assertIn("hit_rate_pct", out)
        self.assertIn("hits", out)
        self.assertIn("miss", out)
        # Total expert accesses > 0
        self.assertGreater(out["hits"] + out["miss"], 0)

    def test_engine_runs_with_cap_1(self):
        """cap=1 (single expert slot per layer) must still work — exercises LRU."""
        r = _run_engine(self.tiny, cap=1, ref=self.tiny / "ref.json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        # With cap=1 and topk=2, every expert access after the first is a miss.
        self.assertGreater(out["miss"], out["hits"])

    def test_engine_runs_with_cap_64(self):
        """cap >> n_experts: no eviction, hit rate should be high."""
        r = _run_engine(self.tiny, cap=64, ref=self.tiny / "ref.json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        # With 4 experts and cap=64, after first pass through layers everything
        # is a hit on the second token.
        self.assertGreater(out["hits"], 0)


class KimiK3DeterminismTest(unittest.TestCase):
    """Same input must produce identical output across runs (no sampling)."""

    @classmethod
    def setUpClass(cls):
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")
        cls.tiny = _generate_tiny_model(C_DIR / "kimik3_tiny")

    def test_two_runs_produce_identical_tokens(self):
        r1 = _run_engine(self.tiny, cap=8, ref=self.tiny / "ref.json")
        r2 = _run_engine(self.tiny, cap=8, ref=self.tiny / "ref.json")
        self.assertEqual(r1.returncode, 0, r1.stderr)
        self.assertEqual(r2.returncode, 0, r2.stderr)
        o1 = _parse_engine_output(r1.stdout)
        o2 = _parse_engine_output(r2.stdout)
        self.assertEqual(o1["c_engine"], o2["c_engine"],
                         "engine is non-deterministic across runs")

    def test_token_ids_in_range(self):
        """Generated token ids must be valid vocab indices [0, vocab)."""
        r = _run_engine(self.tiny, cap=8, ref=self.tiny / "ref.json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        for tid in out["c_engine"]:
            self.assertGreaterEqual(tid, 0)
            self.assertLess(tid, 256, f"token {tid} out of vocab range [0,256)")


class KimiK3PPLModeTest(unittest.TestCase):
    """PPL=1 teacher-forced mode computes NLL/perplexity instead of generating."""

    @classmethod
    def setUpClass(cls):
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")
        cls.tiny = _generate_tiny_model(C_DIR / "kimik3_tiny")

    def test_ppl_mode_reports_nll(self):
        r = _run_engine(self.tiny, cap=8, ref=self.tiny / "ref.json",
                        extra_env={"PPL": "1"})
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        self.assertIn("tf_nll", out, f"PPL=1 mode did not report NLL: {r.stdout}")
        self.assertGreaterEqual(out["tf_nll"], 0.0)  # NLL is non-negative
        # Perplexity = exp(nll), must be finite and positive
        self.assertIn("tf_ppl", out)
        self.assertGreater(out["tf_ppl"], 0.0)
        self.assertFalse(out["tf_ppl"] != out["tf_ppl"], "ppl is NaN")
        self.assertEqual(out["tf_tokens"], 2)  # full_ids has 6, prompt has 4


class KimiK3Int8PathTest(unittest.TestCase):
    """colibri int8 expert path: convert_kimik3.py -> engine runs on converted snapshot."""

    @classmethod
    def setUpClass(cls):
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")
        cls.tiny = _generate_tiny_model(C_DIR / "kimik3_tiny")
        cls.int8 = C_DIR / "kimik3_tiny_i8"
        # Convert tiny -> int8. Skip if numpy/safetensors missing.
        try:
            import numpy  # noqa: F401
            from safetensors.numpy import save_file  # noqa: F401
        except ImportError:
            raise unittest.SkipTest("numpy/safetensors required for int8 conversion")
        if not (cls.int8 / "model.safetensors").exists():
            r = _run([PY, "tools/convert_kimik3.py",
                       "--model", str(cls.tiny), "--out", str(cls.int8)])
            if r.returncode != 0:
                raise unittest.SkipTest(f"convert_kimik3.py failed: {r.stderr}")
            # Copy ref.json for the engine
            shutil.copy2(cls.tiny / "ref.json", cls.int8 / "ref.json")

    def test_int8_engine_runs(self):
        """Engine must accept int8-converted snapshot and produce output."""
        r = _run_engine(self.int8, cap=32, ref=self.int8 / "ref.json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        self.assertIn("c_engine", out, f"no output: {r.stdout}")
        self.assertGreater(len(out["c_engine"]), 0)

    def test_int8_engine_deterministic(self):
        r1 = _run_engine(self.int8, cap=32, ref=self.int8 / "ref.json")
        r2 = _run_engine(self.int8, cap=32, ref=self.int8 / "ref.json")
        self.assertEqual(r1.returncode, 0, r1.stderr)
        self.assertEqual(r2.returncode, 0, r2.stderr)
        o1 = _parse_engine_output(r1.stdout)
        o2 = _parse_engine_output(r2.stdout)
        self.assertEqual(o1["c_engine"], o2["c_engine"])

    def test_int8_engine_reports_int8_load(self):
        """Engine must hit the EXP_INT8 path (no MXFP4 dequantization)."""
        # We can't directly print EXP_INT8 from C, but we can check that the
        # engine runs faster on int8 than MXFP4 (no per-row dequant in the
        # expert cache miss path). Just check that it runs and produces
        # SOMETHING — the int8 path is selected by tensor presence, so the
        # existence of merged_weight in the snapshot is the contract.
        from safetensors import safe_open
        with safe_open(str(self.int8 / "model.safetensors"), framework="numpy") as f:
            keys = list(f.keys())
        merged = [k for k in keys if k.endswith(".merged_weight")]
        qs = [k for k in keys if k.endswith(".qs")]
        self.assertGreater(len(merged), 0, "no merged_weight tensors in int8 snapshot")
        self.assertEqual(len(merged), len(qs), "merged_weight / qs count mismatch")


class KimiK3StabilityTest(unittest.TestCase):
    """Numerical stability: no NaN/Inf in output even with extreme cap values."""

    @classmethod
    def setUpClass(cls):
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")
        cls.tiny = _generate_tiny_model(C_DIR / "kimik3_tiny")

    def test_no_nan_in_generated_tokens(self):
        """All output token ids must be valid integers (not garbage from NaN)."""
        r = _run_engine(self.tiny, cap=4, ref=self.tiny / "ref.json")
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        for tid in out["c_engine"]:
            # NaN cast to int is implementation-defined; if forward pass
            # produced NaN we'd see -1 or huge values here.
            self.assertIsInstance(tid, int)
            self.assertGreaterEqual(tid, 0)

    def test_ppl_mode_finite(self):
        """PPL must be finite (no NaN/Inf in logits under teacher forcing)."""
        r = _run_engine(self.tiny, cap=8, ref=self.tiny / "ref.json",
                        extra_env={"PPL": "1"})
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        self.assertIn("tf_ppl", out)
        # NaN check via "x != x"
        ppl = out["tf_ppl"]
        self.assertEqual(ppl, ppl, "ppl is NaN")
        self.assertLess(ppl, 1e10, "ppl is unreasonably large (model diverged)")


class KimiK3TinyModelTest(unittest.TestCase):
    """Sanity checks on the tiny model generator output."""

    @classmethod
    def setUpClass(cls):
        cls.tiny = _generate_tiny_model(C_DIR / "kimik3_tiny")

    def test_config_has_k3_architecture(self):
        cfg = json.load(open(self.tiny / "config.json"))
        self.assertEqual(cfg["model_type"], "kimi_k3")
        self.assertEqual(cfg["architectures"], ["KimiK3ForConditionalGeneration"])
        tc = cfg["text_config"]
        self.assertEqual(tc["model_type"], "kimi_linear")
        self.assertEqual(tc["hidden_size"], 64)
        self.assertEqual(tc["num_hidden_layers"], 4)
        self.assertEqual(tc["num_experts"], 4)
        self.assertEqual(tc["num_experts_per_token"], 2)
        self.assertEqual(tc["num_shared_experts"], 2)
        self.assertEqual(tc["first_k_dense_replace"], 1)
        # Layer-type config under linear_attn_config (1-indexed)
        lac = tc["linear_attn_config"]
        self.assertEqual(lac["full_attn_layers"], [4])  # layer 3 (0-indexed) is MLA
        self.assertEqual(lac["kda_layers"], [1, 2, 3])  # layers 0,1,2 (0-indexed)

    def test_safetensors_has_required_tensors(self):
        from safetensors import safe_open
        with safe_open(str(self.tiny / "model.safetensors"), framework="numpy") as f:
            keys = set(f.keys())
        # Embeddings + head + final norm
        self.assertIn("language_model.model.embed_tokens.weight", keys)
        self.assertIn("language_model.lm_head.weight", keys)
        self.assertIn("language_model.model.norm.weight", keys)
        # Layer 0 (KDA + dense MLP): has mlp.{gate,up,down}_proj AND KDA attention
        self.assertIn("language_model.model.layers.0.mlp.gate_proj.weight", keys)
        self.assertIn("language_model.model.layers.0.mlp.down_proj.weight", keys)
        self.assertIn("language_model.model.layers.0.self_attn.q_proj.weight", keys)
        self.assertIn("language_model.model.layers.0.self_attn.A_log", keys)
        # Layer 3 (MLA + MoE): has q_a_proj, kv_a_proj_with_mqa, etc.
        self.assertIn("language_model.model.layers.3.self_attn.q_a_proj.weight", keys)
        self.assertIn("language_model.model.layers.3.self_attn.kv_a_proj_with_mqa.weight", keys)
        # Layer 1 (KDA + MoE): has q_proj, k_proj, v_proj, A_log, dt_bias
        self.assertIn("language_model.model.layers.1.self_attn.q_proj.weight", keys)
        self.assertIn("language_model.model.layers.1.self_attn.A_log", keys)
        self.assertIn("language_model.model.layers.1.self_attn.dt_bias", keys)
        # MoE layer (layer 1): gate, routed_expert_*, shared_experts, per-expert packed
        self.assertIn("language_model.model.layers.1.block_sparse_moe.gate.weight", keys)
        self.assertIn("language_model.model.layers.1.block_sparse_moe.routed_expert_down_proj.weight", keys)
        self.assertIn("language_model.model.layers.1.block_sparse_moe.shared_experts.gate_proj.weight", keys)
        # Per-expert MXFP4 tensors
        self.assertIn("language_model.model.layers.1.block_sparse_moe.experts.0.w1.weight_packed", keys)
        self.assertIn("language_model.model.layers.1.block_sparse_moe.experts.0.w1.weight_scale", keys)
        self.assertIn("language_model.model.layers.1.block_sparse_moe.experts.0.w2.weight_packed", keys)
        self.assertIn("language_model.model.layers.1.block_sparse_moe.experts.0.w3.weight_packed", keys)

    def test_ref_json_has_prompt_and_full(self):
        ref = json.load(open(self.tiny / "ref.json"))
        self.assertIn("prompt_ids", ref)
        self.assertIn("full_ids", ref)
        self.assertGreater(len(ref["prompt_ids"]), 0)
        self.assertGreater(len(ref["full_ids"]), len(ref["prompt_ids"]))


class KimiK3CLITest(unittest.TestCase):
    """The `coli` launcher should know about the kimik3 subcommand."""

    @classmethod
    def setUpClass(cls):
        cls.cli = C_DIR / "coli"
        if not cls.cli.exists():
            raise unittest.SkipTest("coli launcher not present")

    def test_coli_help_mentions_kimik3(self):
        r = _run([sys.executable, str(self.cli), "--help"])
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("kimik3", r.stdout.lower())

    def test_coli_kimik3_requires_snap(self):
        """`coli kimik3` with no SNAP env should fail with a clear message."""
        env = dict(os.environ)
        env.pop("SNAP", None)
        env.pop("COLI_MODEL", None)
        r = _run([sys.executable, str(self.cli), "kimik3"], env=env)
        self.assertNotEqual(r.returncode, 0)
        # The error message should point at the missing model dir
        combined = r.stderr + r.stdout
        self.assertTrue("K3 model dir" in combined or "model" in combined.lower(),
                        f"unclear error message: {combined}")


class KimiK3RealConfigTest(unittest.TestCase):
    """Validate the engine against the REAL Kimi-K3 config.json from Hugging Face.

    These tests prove the engine can parse the real K3 configuration and that
    every tensor name the engine expects to load actually exists in the real
    weight map (model.safetensors.index.json). Running the full 2.8T model
    requires ~1TB of storage and is out of scope for CI; config + tensor-name
    compatibility is the correct proxy for "can load real K3 weights".

    The real metadata lives at /workspace/k3_meta (downloaded from
    huggingface.co/moonshotai/Kimi-K3). If absent, tests are skipped.
    """

    REAL_META = Path("/workspace/k3_meta")

    @classmethod
    def setUpClass(cls):
        if not cls.REAL_META.exists():
            raise unittest.SkipTest(f"real K3 metadata not found at {cls.REAL_META}")
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")
        with open(cls.REAL_META / "config.json") as f:
            cls.cfg = json.load(f)
        with open(cls.REAL_META / "model.safetensors.index.json") as f:
            cls.idx = json.load(f)
        cls.weight_map = cls.idx["weight_map"]

    def _run_config_check(self):
        env = dict(os.environ, SNAP=str(self.REAL_META))
        return _run([str(ENGINE), "--config-check"], env=env, timeout=30)

    def test_config_check_exits_zero(self):
        """--config-check must parse the real config.json without error."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_real_config_dimensions(self):
        """Engine reports the exact dimensions from the real K3 config.json."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        cfg1 = out["cfg_lines"][0]
        tc = self.cfg["text_config"]
        self.assertIn(f"hidden={tc['hidden_size']}", cfg1)
        self.assertIn(f"layers={tc['num_hidden_layers']}", cfg1)
        self.assertIn(f"experts={tc['num_experts']}", cfg1)
        self.assertIn(f"topk={tc['num_experts_per_token']}", cfg1)
        self.assertIn(f"shared={tc['num_shared_experts']}", cfg1)
        self.assertIn(f"vocab={tc['vocab_size']}", cfg1)

    def test_real_config_attention_dims(self):
        """Engine reports the exact MLA/KDA attention dimensions."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        cfg2 = out["cfg_lines"][1]
        tc = self.cfg["text_config"]
        self.assertIn(f"q_lora={tc['q_lora_rank']}", cfg2)
        self.assertIn(f"kv_lora={tc['kv_lora_rank']}", cfg2)
        self.assertIn(f"qk_nope={tc['qk_nope_head_dim']}", cfg2)
        self.assertIn(f"qk_rope={tc['qk_rope_head_dim']}", cfg2)
        self.assertIn(f"v_head={tc['v_head_dim']}", cfg2)
        lac = tc["linear_attn_config"]
        self.assertIn(f"kda_heads={lac['num_heads']}", cfg2)
        self.assertIn(f"kda_hd={lac['head_dim']}", cfg2)
        self.assertIn(f"short_conv={lac['short_conv_kernel_size']}", cfg2)

    def test_real_config_layer_counts(self):
        """Layer breakdown: 1 dense (L0), 24 MLA, 68 KDA+MoE = 93 total."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        cfg1 = out["cfg_lines"][0]
        self.assertIn("dense=1", cfg1)
        self.assertIn("MLA=24", cfg1)
        self.assertIn("KDA=68", cfg1)

    def test_real_config_mla_layer_indices(self):
        """MLA layer indices match the 1-indexed full_attn_layers (converted to 0-indexed)."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        # Extract the [CFG] mla_layers: line
        mla_line = [l for l in r.stdout.splitlines() if l.startswith("[CFG] mla_layers:")][0]
        engine_mla = set(int(x) for x in mla_line.split(":", 1)[1].split())
        # Config uses 1-indexed: layer v in full_attn_layers -> layer v-1 is MLA
        tc = self.cfg["text_config"]
        expected_mla = set(v - 1 for v in tc["linear_attn_config"]["full_attn_layers"])
        self.assertEqual(engine_mla, expected_mla,
                         f"MLA layers mismatch: engine={sorted(engine_mla)} expected={sorted(expected_mla)}")
        self.assertEqual(len(engine_mla), 24)

    def test_real_config_kda_layer_indices(self):
        """KDA layer indices match the 1-indexed kda_layers (converted to 0-indexed, MoE only)."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        kda_line = [l for l in r.stdout.splitlines() if l.startswith("[CFG] kda_layers:")][0]
        engine_kda = set(int(x) for x in kda_line.split(":", 1)[1].split())
        # Config: kda_layers lists 1-indexed layer numbers; engine excludes layer 0
        # (which is KDA attention + dense MLP, categorised as "dense").
        tc = self.cfg["text_config"]
        expected_kda_moe = set(v - 1 for v in tc["linear_attn_config"]["kda_layers"] if (v - 1) >= tc["first_k_dense_replace"])
        self.assertEqual(engine_kda, expected_kda_moe,
                         f"KDA layers mismatch: engine={sorted(engine_kda)} expected={sorted(expected_kda_moe)}")
        self.assertEqual(len(engine_kda), 68)

    def test_real_config_dense_layer_is_zero(self):
        """Layer 0 is the dense MLP layer (first_k_dense_replace=1)."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        dense_line = [l for l in r.stdout.splitlines() if l.startswith("[CFG] dense_layer:")][0]
        engine_dense = [int(x) for x in dense_line.split(":", 1)[1].split()]
        self.assertEqual(engine_dense, [0])

    def test_real_config_activation_params(self):
        """SiTU activation parameters match the real config."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        cfg3 = out["cfg_lines"][2]
        tc = self.cfg["text_config"]
        self.assertIn(f"situ_beta={tc['activation_situ_beta']:.1f}", cfg3)
        self.assertIn(f"situ_lin_beta={tc['activation_situ_linear_beta']:.1f}", cfg3)
        # Engine uses C %.1e format (e.g. "1.0e-05"), not Python's default "1e-05"
        self.assertIn(f"eps={tc['rms_norm_eps']:.1e}", cfg3)

    def test_real_config_moe_renormalize_is_true(self):
        """moe_renormalize=true must be parsed correctly (JSON boolean, not number)."""
        r = self._run_config_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        out = _parse_engine_output(r.stdout)
        cfg3 = out["cfg_lines"][2]
        self.assertIn("moe_renorm=1", cfg3)

    # --- tensor name compatibility with real weight map ---

    def _has_tensor(self, pattern_prefix):
        """Check if any real tensor starts with the given prefix."""
        return any(k.startswith(pattern_prefix) for k in self.weight_map)

    def test_real_weights_have_embed_and_head(self):
        """Embedding, LM head, and final norm tensors exist in real weights."""
        wm = self.weight_map
        self.assertIn("language_model.model.embed_tokens.weight", wm)
        self.assertIn("language_model.lm_head.weight", wm)
        self.assertIn("language_model.model.norm.weight", wm)

    def test_real_weights_have_mla_tensors(self):
        """All MLA tensor names the engine loads exist in the real weights."""
        wm = self.weight_map
        # Layer 3 is the first MLA layer (0-indexed)
        base = "language_model.model.layers.3.self_attn."
        for suffix in ["q_a_proj.weight", "q_a_layernorm.weight", "q_b_proj.weight",
                       "kv_a_proj_with_mqa.weight", "kv_a_layernorm.weight",
                       "kv_b_proj.weight", "o_proj.weight", "g_proj.weight"]:
            self.assertIn(base + suffix, wm, f"missing MLA tensor: {base + suffix}")

    def test_real_weights_have_kda_tensors(self):
        """All KDA tensor names the engine loads exist in the real weights."""
        wm = self.weight_map
        # Layer 0 is KDA attention + dense MLP
        base = "language_model.model.layers.0.self_attn."
        for suffix in ["q_proj.weight", "k_proj.weight", "v_proj.weight",
                       "q_conv1d.weight", "k_conv1d.weight", "v_conv1d.weight",
                       "A_log", "dt_bias", "b_proj.weight",
                       "f_a_proj.weight", "f_b_proj.weight", "g_proj.weight",
                       "o_norm.weight", "o_proj.weight"]:
            self.assertIn(base + suffix, wm, f"missing KDA tensor: {base + suffix}")

    def test_real_weights_have_dense_mlp_tensors(self):
        """Dense MLP tensors (layer 0) exist in the real weights."""
        wm = self.weight_map
        base = "language_model.model.layers.0.mlp."
        for suffix in ["gate_proj.weight", "up_proj.weight", "down_proj.weight"]:
            self.assertIn(base + suffix, wm, f"missing dense MLP tensor: {base + suffix}")

    def test_real_weights_have_moe_tensors(self):
        """MoE router, shared experts, and latent projection tensors exist."""
        wm = self.weight_map
        base = "language_model.model.layers.1.block_sparse_moe."
        for suffix in ["gate.weight", "gate.e_score_correction_bias",
                       "routed_expert_down_proj.weight", "routed_expert_up_proj.weight",
                       "routed_expert_norm.weight",
                       "shared_experts.gate_proj.weight", "shared_experts.up_proj.weight",
                       "shared_experts.down_proj.weight"]:
            self.assertIn(base + suffix, wm, f"missing MoE tensor: {base + suffix}")

    def test_real_weights_have_mxfp4_expert_tensors(self):
        """Per-expert MXFP4 packed weights + scales exist for all 896 experts."""
        wm = self.weight_map
        # Check experts 0, 1, 100, 895 (first, second, middle, last)
        for e in [0, 1, 100, 895]:
            base = f"language_model.model.layers.1.block_sparse_moe.experts.{e}."
            for w in ["w1", "w2", "w3"]:
                self.assertIn(base + f"{w}.weight_packed", wm, f"missing expert {e} {w}.weight_packed")
                self.assertIn(base + f"{w}.weight_scale", wm, f"missing expert {e} {w}.weight_scale")

    def test_real_weights_have_layernorms(self):
        """Input and post-attention layernorms exist for all 93 layers."""
        wm = self.weight_map
        for i in range(93):
            self.assertIn(f"language_model.model.layers.{i}.input_layernorm.weight", wm,
                          f"missing input_layernorm for layer {i}")
            self.assertIn(f"language_model.model.layers.{i}.post_attention_layernorm.weight", wm,
                          f"missing post_attention_layernorm for layer {i}")

    def test_real_weights_expert_count_matches_config(self):
        """Each MoE layer has exactly num_experts (896) experts."""
        wm = self.weight_map
        tc = self.cfg["text_config"]
        n_experts = tc["num_experts"]
        # Check layers 1, 50, 92 (first, middle, last MoE layer)
        for layer in [1, 50, 92]:
            count = sum(1 for k in wm
                        if k.startswith(f"language_model.model.layers.{layer}.block_sparse_moe.experts.")
                        and ".w1.weight_packed" in k)
            self.assertEqual(count, n_experts,
                             f"layer {layer}: expected {n_experts} experts, found {count}")

    def test_real_weights_total_tensor_count(self):
        """Total tensor count matches the real K3 weight map (sanity check)."""
        # 497220 tensors is the known count for the real K3 model
        self.assertEqual(len(self.weight_map), 497220,
                         f"unexpected tensor count: {len(self.weight_map)}")


class KimiK3RealWeightsLoadTest(unittest.TestCase):
    """Load REAL Kimi-K3 weights from HuggingFace safetensors shards.

    This is the actual "can the engine load real K3 weights" verification.
    Two shards (model-00001 and model-00094, ~7GB total) are downloaded from
    huggingface.co/moonshotai/Kimi-K3 to /workspace/k3_real. These contain:
      - shard 00001: layer 0 in full (KDA attention + dense MLP) — 23 tensors
      - shard 00094: embed_tokens + lm_head + final norm + output_attn_res — 5 tensors

    The engine's --load-check mode reads each tensor's bf16 -> fp32 sample and
    verifies the deserialization produces finite, non-trivial weights. This
    exercises the actual code path used at inference time (st_read_f32,
    bf16_to_f32, multi-shard indexing via st_init).

    Skipped if the real weights are not present (e.g. running offline).
    """

    REAL_WEIGHTS = Path("/workspace/k3_real")

    @classmethod
    def setUpClass(cls):
        if not (cls.REAL_WEIGHTS / "model-00001-of-000096.safetensors").exists():
            raise unittest.SkipTest(
                f"real K3 weights not present at {cls.REAL_WEIGHTS}; "
                "download with: hf download moonshotai/Kimi-K3 "
                "model-00001-of-000096.safetensors model-00094-of-000096.safetensors "
                "--local-dir /workspace/k3_real"
            )
        if not _build_engine():
            raise unittest.SkipTest("kimik3 build failed")

    def _run_load_check(self):
        env = dict(os.environ, SNAP=str(self.REAL_WEIGHTS))
        return _run([str(ENGINE), "--load-check"], env=env, timeout=60)

    def test_load_check_exits_zero(self):
        """--load-check must complete successfully against real weights."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_load_check_indexes_two_shards(self):
        """Multiple shards must be indexed (layer 0 + layer 1-4 + embed/head)."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        # Header line: "== load-check: N shards indexed (M tensors) =="
        # We download shards 00001 (layer 0) + 00094 (embed/head) + 00002-00005 (layers 1-4).
        # The exact shard count grows as more are downloaded; assert >= 2 and tensors > 28.
        header = [l for l in r.stdout.splitlines() if "shards indexed" in l][0]
        import re
        m = re.search(r"(\d+) shards indexed \((\d+) tensors\)", header)
        self.assertIsNotNone(m, f"header format unexpected: {header}")
        n_shards = int(m.group(1))
        n_tensors = int(m.group(2))
        self.assertGreaterEqual(n_shards, 2, f"expected >=2 shards, got {n_shards}: {header}")
        self.assertGreater(n_tensors, 28, f"expected >28 tensors, got {n_tensors}: {header}")

    def test_no_nan_or_zero_tensors(self):
        """Every present tensor must be finite and non-trivially nonzero."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        summary = [l for l in r.stdout.splitlines() if "summary" in l][0]
        # Format: == load-check summary: OK=N  MISSING=M  NaN=0  ZERO=0 ==
        self.assertIn("NaN=0", summary, f"NaN tensors detected: {summary}")
        self.assertIn("ZERO=0", summary, f"all-zero tensors detected: {summary}")
        self.assertGreater(summary.count("OK="), 0)

    def test_mxfp4_expert_tensors_dequantized(self):
        """MXFP4 expert weights (weight_packed + weight_scale) must be present
        on downloaded MoE layers and dequantize to plausible values.
        Verifies the real-K3 MXFP4 layout matches our dequant path."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        # Layer 1 (downloaded as shard 00002) has experts with MXFP4 weights.
        # Expert 0, w1.weight_packed must appear as OK-MXFP4 in output.
        mxfp4_lines = [l for l in r.stdout.splitlines() if "OK-MXFP4" in l]
        self.assertGreater(len(mxfp4_lines), 0, "no MXFP4 expert tensors dequantized")
        # Verify layer 1 expert 0 w1 packed + scale both present
        self.assertTrue(
            any("layers.1.block_sparse_moe.experts.0.w1.weight_packed" in l for l in mxfp4_lines),
            "layer 1 expert 0 w1.weight_packed not dequantized"
        )
        self.assertTrue(
            any("layers.1.block_sparse_moe.experts.0.w1.weight_scale" in l for l in mxfp4_lines),
            "layer 1 expert 0 w1.weight_scale not dequantized"
        )
        # Scales must be small positive values (typical expert weight scale ~0.01)
        scale_line = [l for l in mxfp4_lines if "experts.0.w1.weight_scale" in l][0]
        self.assertIn("min=+", scale_line)  # scales are always positive (E8M0)

    def test_layer_zero_tensors_loaded(self):
        """Layer 0 (KDA attention + dense MLP) tensors must be present and OK."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        layer0_tensors = [
            "language_model.model.layers.0.self_attn.q_proj.weight",
            "language_model.model.layers.0.self_attn.k_proj.weight",
            "language_model.model.layers.0.self_attn.v_proj.weight",
            "language_model.model.layers.0.self_attn.A_log",
            "language_model.model.layers.0.self_attn.dt_bias",
            "language_model.model.layers.0.self_attn.b_proj.weight",
            "language_model.model.layers.0.self_attn.f_a_proj.weight",
            "language_model.model.layers.0.self_attn.f_b_proj.weight",
            "language_model.model.layers.0.self_attn.g_proj.weight",
            "language_model.model.layers.0.self_attn.o_norm.weight",
            "language_model.model.layers.0.self_attn.o_proj.weight",
            "language_model.model.layers.0.mlp.gate_proj.weight",
            "language_model.model.layers.0.mlp.up_proj.weight",
            "language_model.model.layers.0.mlp.down_proj.weight",
            "language_model.model.layers.0.input_layernorm.weight",
            "language_model.model.layers.0.post_attention_layernorm.weight",
        ]
        for name in layer0_tensors:
            # Find the line that mentions this exact tensor name
            lines = [l for l in r.stdout.splitlines() if name in l]
            self.assertEqual(len(lines), 1, f"tensor {name} not in load-check output")
            line = lines[0]
            self.assertTrue(line.startswith("  OK"),
                             f"{name}: expected OK, got {line!r}")

    def test_embed_and_lm_head_loaded(self):
        """Embedding, LM head, final norm tensors must load with reasonable values."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        for name in ["embed_tokens.weight", "lm_head.weight", "model.norm.weight"]:
            lines = [l for l in r.stdout.splitlines() if name in l and "OK" in l]
            self.assertEqual(len(lines), 1, f"{name}: no OK line in output")
            # Verify the engine reported a min and max (non-trivial weights)
            line = lines[0]
            self.assertIn("min=", line)
            self.assertIn("max=", line)

    def test_embed_tensor_size_matches_real_k3(self):
        """embed_tokens must report the exact numel of the real K3 (1.17B params)."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        line = [l for l in r.stdout.splitlines() if "embed_tokens.weight" in l and "OK" in l][0]
        # hidden_size=7168, vocab=163840 -> 7168*163840 = 1174405120
        self.assertIn("numel=1174405120", line, f"unexpected embed size: {line}")

    def test_layer0_q_proj_size_matches_real_k3(self):
        """layer 0 q_proj has expected numel: kda_heads*kda_hd * hidden = 96*128*7168."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        line = [l for l in r.stdout.splitlines()
                if "layers.0.self_attn.q_proj.weight" in l and "OK" in l][0]
        # 96 * 128 * 7168 = 88080384
        self.assertIn("numel=88080384", line, f"unexpected q_proj size: {line}")

    def test_a_log_has_realistic_range(self):
        """KDA A_log (log retention factor) should be in a plausible range.

        A_log values are exp(-A) where A controls retention decay; typical
        range is [-1, 3]. This catches garbage bf16 reads (e.g. bit-flips
        would produce values like 1e30 or NaN)."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        line = [l for l in r.stdout.splitlines() if "self_attn.A_log" in l and "OK" in l][0]
        # Extract min/max from "min=X max=Y mean=Z"
        import re
        m = re.search(r"min=([+\-0-9.eE]+).*max=([+\-0-9.eE]+)", line)
        self.assertIsNotNone(m, f"could not parse min/max from: {line}")
        mn, mx = float(m.group(1)), float(m.group(2))
        self.assertGreater(mn, -10.0, f"A_log min {mn} implausibly negative")
        self.assertLess(mx, 10.0, f"A_log max {mx} implausibly large")
        self.assertNotEqual(mn, mx, "A_log all-same — likely misread as constant")

    def test_missing_tensors_reported_for_layers_not_downloaded(self):
        """Layers 1..92 are not downloaded, so they must be reported MISSING."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        summary = [l for l in r.stdout.splitlines() if "summary" in l][0]
        # We only downloaded layer 0 (23 tensors) + embed/head (5 tensors) = 28 OK.
        # The remaining tensors of layers 1..92 (each ~26 tensors x 92 layers + ...)
        # must be MISSING. We don't assert an exact count (it depends on which
        # layer types are checked), but it must be > 1000.
        import re
        m = re.search(r"MISSING=(\d+)", summary)
        self.assertIsNotNone(m, f"could not parse MISSING count: {summary}")
        missing = int(m.group(1))
        self.assertGreater(missing, 1000, f"too few MISSING tensors: {missing}")

    def test_deserialization_completes_with_ok_summary(self):
        """The very last line must confirm successful deserialization."""
        r = self._run_load_check()
        self.assertEqual(r.returncode, 0, r.stderr)
        last = r.stdout.strip().splitlines()[-1]
        self.assertIn("[OK]", last)
        self.assertIn("deserialization", last.lower())


if __name__ == "__main__":
    unittest.main()
